spring.application.name=FullStackFlow

management.endpoints.web.exposure.include=*

server.port=8080

#management.endpoints.web.cors.allowed-origins=http://localhost:5173
#management.endpoints.web.cors.allowed-methods=GET