on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Jar
        run: mvn clean package -DskipTests

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Create deployment folder
        run: |
          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p /home/${{ secrets.EC2_USER }}/app"

      # Bug: Hardcoded ec2-user instead of using the secret
      - name: Copy Jar To EC2
        run: |
          scp -i private_key.pem \
          -o StrictHostKeyChecking=no \
          target/*.jar \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/app.jar

      - name: Debug SSH
        run: |
         echo "Host: ${{ secrets.EC2_HOST }}"
         echo "User: ${{ secrets.EC2_USER }}"
         cat private_key.pem | head -3
         nc -zv ${{ secrets.EC2_HOST }} 22 || echo "PORT 22 UNREACHABLE"
         ssh -i private_key.pem \
         -o StrictHostKeyChecking=no \
         -o ConnectTimeout=10 \
         -v \
         ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
         "echo SSH_SUCCESS" 2>&1 || echo "EXIT CODE: $?" 

      #  ^^^ use the secret here
      - name: Test SSH Connection
        run: |
          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          -v \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "echo connected"

      - name: Stop Application
        run: |
          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "reached remote shell"
            pkill -f 'app.jar' || true
            echo "pkill done: $?"
          EOF

      - name: Start Application
        run: |
          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app
            nohup java -jar app.jar > app.log 2>&1 < /dev/null &
            echo "Started with PID: $!"
          EOF